### ISSUE TITLE
bug(customrpc): 

### ISSUE THREAD

**Issue by glitch65** [nexpid/VendettaPlugins#27]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@g11itch

### Detailed Info

can't change plugin settings

### Steps to Reproduce

1. open plugin list 
2. open plugin settings
3. boom you can't do anything 

### System Info

Device: realme RMX3191
Model: RMX3191
Manufacturer: realme
Brand: realme

OS: Android
Version: 13

Discord Branch: googleRelease
Discord Version: 194.17
Discord Build: 194017
Vendetta Version: d539e5a

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
what

**Comment by nexpid** [comment]
closing this because you haven't even titled it correctly
