### ISSUE TITLE
bug(customrpc): 

### ISSUE THREAD

**Issue by MRVIP219** [nexpid/VendettaPlugins#28]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@t_ps

### Detailed Info

When I click to enable it nothing happened 

### Steps to Reproduce

Plugins
CustomRPC
nothing happened 

### Crash Info

No

### Bug Screenshot

![Screenshot_٢٠٢٣٠٩٠٩_١٥٤٠٣٨](https://github.com/nexpid/VendettaPlugins/assets/133910851/cf9189b3-f8ce-4958-a313-bf1083fccb61)

### System Info

Device: samsung SM-A035F
Model: SM-A035F
Manufacturer: samsung
Brand: samsung

OS: Android
Version: 13

Discord Branch: googleRelease
Discord Version: 193.13
Discord Build: 193013
Vendetta Version: d539e5a

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
please title the bug properly next time. make sure to enable "Display Activity" and enable the "Display current activity as a status message" in "Privacy & Safety" in settings, thanks
