### ISSUE TITLE
bug(customrpc): 

### ISSUE THREAD

**Issue by glitch65** [nexpid/VendettaPlugins#29]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@g11itch

### Detailed Info

it is impossible to somehow configure the plugin 

### Steps to Reproduce

1.I will show you on video

### Bug Screenshot

![video](https://media.discordapp.net/attachments/1073902493156769794/1150054036645629992/Record_2023-09-09-22-02-54.mp4)

### System Info

Device: realme RMX3191
Model: RMX3191
Manufacturer: realme
Brand: realme

OS: Android
Version: 13

Discord Branch: betaRelease
Discord Version: 195.15
Discord Build: 195115
Vendetta Version: d539e5a

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
also the video doesn't work

**Comment by glitch65** [comment]
https://media.discordapp.net/attachments/1073902493156769794/1150054036645629992/Record_2023-09-09-22-02-54.mp4

**Comment by nexpid** [comment]
what did you do before that?

**Comment by glitch65** [comment]
at first everything was fine, then it stopped working, I installed a stable version of Discord and cleared the plugin data, completely reinstalled Discord and the plugin itself

**Comment by glitch65** [comment]
at first everything was fine, then it stopped working, I installed a stable version of Discord and cleared the plugin data, completely reinstalled Discord and the plugin itself
