### ISSUE TITLE
bug(themes+): plugin settings doesn't work

### ISSUE THREAD

**Issue by Vercixx** [nexpid/VendettaPlugins#30]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@vercixx_cool

### Detailed Info

it's impossible to configure plugin's settings

### Steps to Reproduce

1. go to settings
2. go to plugin list
3. configure themes+ plugin
4. nothing can be changed

### Crash Info

bug doesn't causes a crash

### Bug Screenshot

![image](https://github.com/nexpid/VendettaPlugins/assets/112702555/02ac3a9d-7ac2-484e-b7d3-0de8ac12daef)
nothing expect "why themes+ inactive?" and "custom icon pack" link working

### System Info

Device: iPhone 12 mini
Manufacturer: Apple
Brand: iPhone

OS: iOS 16.6 (not jailbroken)
Version: iOS 16.6

Discord Branch: ptb
Discord Version: 191.0
Discord Build: 47806
Vendetta Version: d539e5a

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by Vercixx** [comment]
oops, accidentally closed issue

**Comment by nexpid** [comment]
yeah, you're not supposed to edit anything lol

**Comment by nexpid** [comment]
it uses themes+ settings from the theme you're using

**Comment by nexpid** [comment]
https://github.com/nexpid/VendettaThemesPlus/wiki
