### ISSUE TITLE
bug(customrpc): plugin settings doesn't work

### ISSUE THREAD

**Issue by Vercixx** [nexpid/VendettaPlugins#31]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@vercixx_cool

### Detailed Info

can't interact with plugin's settings

### Steps to Reproduce

1. go to settings
2. go to plugin list
3. go to custom rpc settings
4. and you can do nothing

### Crash Info

bug doesn't cause a crash

### Bug Screenshot

![IMG_0783](https://github.com/nexpid/VendettaPlugins/assets/112702555/d2d57a53-44aa-4105-955a-5fc73c60c5bd)
nothing happening if i press somewhere here

### System Info

Device: iPhone 12 mini
Manufacturer: Apple
Brand: iPhone

OS: iOS 16.6 (not jailbroken)
Version: iOS 16.6

Discord Branch: ptb
Discord Version: 191.0
Discord Build: 47806
Vendetta Version: d539e5a

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
has been fixed
