### ISSUE TITLE
suggest(NEXXUTILS): Restore emoji hold in reaction picker

### ISSUE THREAD

**Issue by Quinxxxx** [nexpid/VendettaPlugins#32]
### Check all the boxes below

- [X] I have checked that this feature hasn't already been suggested

### Discord username

moodle.v2

### Simple description

On the old discord app, if you held a message > click reaction button > reaction picker opens. You could long press an emoji to open the emoji info popup. On the latest discord RN versions this doesn't seem to work so if it was to be added into nexxutils would be beautiful :)

### Elaborate

N/A

**Comment by nexpid** [comment]
will be added

**Comment by nexpid** [comment]
was added
