### ISSUE TITLE
bug(customrpc): no input fields

### ISSUE THREAD

**Issue by Vercixx** [nexpid/VendettaPlugins#34]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@vercixx_cool

### Detailed Info

can only change it using "copy json" and "load from clipboard"

### Steps to Reproduce

1. go to settings
2. go to plugins
3. go to custom rpc settings
4. for example, try changing button url
5. no input field

### Crash Info

no crashes

### Bug Screenshot

![IMG_0811](https://github.com/nexpid/VendettaPlugins/assets/112702555/3fe62ad4-c1e0-4877-912f-141381c9d2db)

### System Info

Device: iPhone13,1
Model: iPhone
Manufacturer: Apple Inc.
Brand: iPhone

OS: iOS
Version: 16.6.1

Discord Branch: ptb
Discord Version: 191.0
Discord Build: 47806
Vendetta Version: d539e5a

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
there is an input field, that's nexxutil's fault for not showing it properly lol. it's highly in beta
