### ISSUE TITLE
bug(usrpfp): Lag issues

### ISSUE THREAD

**Issue by DarkLePauvre** [nexpid/VendettaPlugins#37]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@darklepauvre

### Detailed Info

Reduces your fps drastically (like alot) and makes it almost impossible to do anything 

### Steps to Reproduce

1. Install the plugin
2. Load alot of messages with animated pfp
3. Vendetta is now super laggy
(Btw i don't know if it's the same for anyone but i think my phone loads gifs even if it's not animated)

### System Info

Device: (Joyeuse) Redmi Note 9 Pro
Manufacturer: Xiaomi
Brand: Redmi

OS: Android | MIUI
Version: 11 | 12.5

Discord Branch: Stable
Discord Version: 196.16 (196016)
Discord Build: JS 19601600121623
Vendetta Version: d539e5a

React Version: 18.2.0
Hermes Bytecode: Bytecode - 94

**Comment by nexpid** [comment]
should be fixed as of now
