### ISSUE TITLE
bug(cloud-sync): After latest update, Discord on iOS crashed

### ISSUE THREAD

**Issue by dora727** [nexpid/VendettaPlugins#39]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@dor4a

### Detailed Info

After latest update, CloudSync crashed Discord each time I opened Discord, until I disable it by turning off the internet
Phone: iPhone SE 2022, iOS 16.4
Discord version: 197.0 (50096)

### Steps to Reproduce

1. Enable CloudSync
2. Discord crashed

### Crash Info

https://pastebin.com/raw/nuACtUXz
^ the .ips crash log

### System Info

Device: iPhone SE 2022
Manufacturer: Apple(?)
Brand: Apple(?)

OS: iOS
Version: 16.4

Discord Branch: Beta
Discord Version: 197.0
Discord Build: 50096
Vendetta Version: d539e5a

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
asked @acquitelol and apparently vendetta's crashing on ios a lot lately, you should just disable cloud sync for now

**Comment by QuanTrieuPCYT** [comment]
Reinstalled my Discord client and this happened, also waiting for a fix :eyes:

**Comment by dora727** [comment]
alr this is now fixed so ima close this
