### ISSUE TITLE
bug(NEXXUTILS): Send Spotify invite does not work

### ISSUE THREAD

**Issue by Quinxxxx** [nexpid/VendettaPlugins#41]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

moodle.v2

### Detailed Info

The send Spotify invite does not work
![Screenshot_2023-10-16-22-13-11-70_ce48f3669154ad2f53ee7715a6cfbfc3](https://github.com/nexpid/VendettaPlugins/assets/88912716/06e8eb60-5194-46b3-a3f8-41b05fabdefe)

### Steps to Reproduce

1. Turn on "Send Spotify invite"
2. Open server or DM chat
3. Click add attachment button
4. Click "Send Spotify invite" button 

### Bug Screenshot

![Screenshot_2023-10-16-22-15-04-78_ce48f3669154ad2f53ee7715a6cfbfc3](https://github.com/nexpid/VendettaPlugins/assets/88912716/18a144d8-9e62-4cfe-8247-6a13e46c4958)

### System Info

Device: OnePlus 11 (CPH2449)
Manufacturer: OnePlus 
Brand: OnePlus 

OS: Android 
Version: 13

Discord Branch: BetaRelease
Discord Version: 200.8
Discord Build: 200108
Vendetta Version: 2cc1f8d

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
https://github.com/nexpid/VendettaPlugins/commit/14f3b11f8ab9a818ca133cb0fe4a9324da61bb5e
