### ISSUE TITLE
bug(NexxUtils): using ``Restore emoji info in reaction picker`` Crashes Vendetta

### ISSUE THREAD

**Issue by Rairof** [nexpid/VendettaPlugins#42]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@Rairof

### Detailed Info

``Restore emoji info in reaction picker`` function seems to crash vendetta on 199.14 beta version.

### Steps to Reproduce

1. Enable NexxUtils plugin
2. Enable ``Restore emoji info in reaction picker`` toggle
3. Go to any message and long press and open reaction picker
4. Long press any emojis.
5. Discord crashes.

### Crash Info

N/A

### Bug Screenshot

``Restore emoji info in reaction picker`` crash logs-
![Screenshot_2023-10-17-02-38-36-300_dev beefers vendetta-edit](https://github.com/nexpid/VendettaPlugins/assets/107706560/eacd26d8-627f-4ffe-8ff4-e2bc7f1ed7de)

![Screenshot_2023-10-17-02-38-28-403_dev beefers vendetta-edit](https://github.com/nexpid/VendettaPlugins/assets/107706560/6e41732a-a4c4-4663-8798-8839b5aeea25)

### System Info

Device: Xiaomi 11T Pro (2107113SI)
Manufacturer: Xiaomi
Brand: Xiaomi

OS: MIUI based on Android 
Version: 13

Discord Branch: BetaRelease
Discord Version: 199.14
Discord Build: 199114
Vendetta Version: 2cc1f8d

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
i'm gonna assume this doesn't happen anymore

**Comment by Rairof** [comment]
@nexpid still happens.

https://github.com/nexpid/VendettaPlugins/assets/107706560/6d561625-51c5-4235-96a2-e1cc6983c16a

**Comment by nexpid** [comment]
and what version are you on

**Comment by nexpid** [comment]
that's the issue then, you're on an outdated version
update to 201.13 atleast

**Comment by Rairof** [comment]
https://github.com/nexpid/VendettaPlugins/issues/42#issuecomment-1783322897
I would update it but a certain experiment named "media mosaic" is removed on all newer version experiments after 200 and above, hence I'm sticking with 199.14 beta until that plugin is developed. This also makes things harder as most of the plugins are starting to drop support for 199.14 understandably... I'm suck as you can see

**Comment by Rairof** [comment]
@nexpid update- just installed discord 202.16 beta and it doesn't work.
![Screenshot_2023-10-28-17-27-48-501_dev beefers vendetta-edit](https://github.com/nexpid/VendettaPlugins/assets/107706560/8e008eea-697f-493b-845a-0662b1ea4ea3)
