### ISSUE TITLE
suggest(NexxUtils): ``Send Spotify link`` feature actually working

### ISSUE THREAD

**Issue by Rairof** [nexpid/VendettaPlugins#43]
### Check all the boxes below

- [X] I have checked that this feature hasn't already been suggested

### Discord username

@Rairof

### Simple description

The current Spotify listen along link feature just redirects users to Spotify app instead of actually joining in listen along session, it is the expected behaviour in mobile with listen along links but it's neither ideal not useful so let's fix that with this workaround. I don't know if this is possible or not so it's upto Nexpid. Thank you in advance.

![Screenshot_2023-10-18-05-23-41-408_dev beefers vendetta-edit](https://github.com/nexpid/VendettaPlugins/assets/107706560/d62f9346-8caa-4396-9949-84306ce05e77)

### Elaborate

Issue- 
The ``Send Spotify invite`` toggle sends the listen along link but clicking on join just redirects users to Spotify current playing track instead of joining in listen along session which isn't intended behaviour for listen along feature.

Expected behaviour- 
Clicking on "Join" button makes user join in the listen along session instead.

Fix-
Hook user spotify current playing song profile listen along button with ``Spotify listen along invite`` "Join" button and clicking join button opens Spotify app in background then triggering listen along feature.
![IMG_20231018_053529](https://github.com/nexpid/VendettaPlugins/assets/107706560/bf09f28f-732a-4206-a252-5ce0a7119d5f)

**Comment by nexpid** [comment]
not sure if this is actually possible, closing this for now
if i figure something out i'll reopen this
