### ISSUE TITLE
suggest(doom): DOOM II

### ISSUE THREAD

**Issue by Celestemysterios** [nexpid/VendettaPlugins#46]
### Check all the boxes below

- [X] I have checked that this feature hasn't already been suggested

### Discord username

celestemyst

### Simple description

DOOM II in discord basically 

### Elaborate

copy paste time
maybe add myhouse (atleast the wad ver but if your able to somehow do the pk3 ver i will like you and give you cookie)
also maybe add a selecter in the DOOM plugin to choose what DOOM you want to play

also support for saving

**Comment by nexpid** [comment]
finally finished this lmao yaay!!!

**Comment by nexpid** [comment]
closed by 1f766777c536090e80f89383e30eeda6bb0bdd8c
