### ISSUE TITLE
bug(local-pins): messages do not show with new channel details sheet

### ISSUE THREAD

**Issue by PalmDevs** [nexpid/VendettaPlugins#47]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@palmdevs

### Detailed Info

Locally pinned messages do not show in Tabs V2 with the new channel details sheet design toggle enabled at all.

### Steps to Reproduce

1. Install the plugin
2. Install Experiments plugin (and disable updates then reload, if it's not working)
3. Enable Tabs V2 via switch
4. Enable DevTools via switch
5. Toggle on the `New channel details sheet` design toggle using DevTools (make sure to check the codename for the toggle, if it is `disable_(...)`, just leave it as is)
6. Select a message and pin it locally
7. Check pins tab in channel info

### Bug Screenshot

Message was pinned (there's an unpin option)  
![Screenshot_20231031_204516_Discord](https://github.com/nexpid/VendettaPlugins/assets/67689562/ad59d0be-e68e-49c3-900d-1c86eb6deadf)

The message was not shown in the Pins tab  
![Screenshot_20231031_204450_Discord](https://github.com/nexpid/VendettaPlugins/assets/67689562/1d87bbc8-ac6a-4c20-9aa5-73cf853e18bc)

### System Info

Device: SM-A135F
Manufacturer: Samsung
Brand: Samsung Galaxy A13

OS: Android
Version: 13 (API 33)

Discord Branch: Alpha
Discord Version: 204.0
Discord Build: 20400
Vendetta Version: 289ffa4

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
fixed but not committed yet

**Comment by nexpid** [comment]
closed by bbe0eb7280cb1a118e5e5e30d48fc553da034f21
