### ISSUE TITLE
Make the text readable on monet theme generator

### ISSUE THREAD

**Issue by Joeeeeb5** [nexpid/VendettaPlugins#48]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@192.168.0.76

### Detailed Info

Text is yellow, background is also yellow

### Steps to Reproduce

Install the plugin and try to read text

### System Info

Device: poco m3
Manufacturer: xiaomi
Brand: poco

OS: android 12 miui 14
Version: that one

Discord Branch: stable
Discord Version: latest one from stable idk
Discord Build: what
Vendetta Version: newest

React Version: surprised
Hermes Bytecode: no

**Comment by JapanYoshi** [comment]
I have also generated a theme from that generator, and the text comes out dark grey and barely readable.

**Comment by nexpid** [comment]
https://github.com/nexpid/VendettaPlugins/commit/948c4ddb1b18b8ec4ca4a8907a30092729d3260c

**Comment by Joeeeeb5** [comment]
how do i dl it tho
