### ISSUE TITLE
bug(PLUGIN): Plugin Browser sorting and searching

### ISSUE THREAD

**Issue by 7heMech** [nexpid/VendettaPlugins#49]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

7heMech

### Detailed Info

The plugin browser has an issue with filtering and sorting content, I think you might need to set some keys.

### Steps to Reproduce

1. Go to plugins menu and:
![ResizedImage_2023-11-17_09-01-06_2116](https://github.com/nexpid/VendettaPlugins/assets/83923848/bd910fc0-8438-42ff-b37e-4a718f283442)
![ResizedImage_2023-11-17_09-03-59_2575](https://github.com/nexpid/VendettaPlugins/assets/83923848/3718c3d7-3d05-4916-a431-1b9d90b29f3f)
![ResizedImage_2023-11-17_09-05-10_1791](https://github.com/nexpid/VendettaPlugins/assets/83923848/f0df62bc-e85a-4b70-b202-4bf8495b3f99)
Look at the buttons of the last two plugins.

### System Info

All latest.

**Comment by nexpid** [comment]
https://github.com/nexpid/VendettaPlugins/commit/adf11c7a51d1043060ee86597b73492b5322b459
