### ISSUE TITLE
bug(Plugin Browser): Search doesn't work

### ISSUE THREAD

**Issue by 7heMech** [nexpid/VendettaPlugins#52]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

7heMech

### Detailed Info

The plugin browser has an issue with searching.

### Steps to Reproduce

1. Go to plugins menu
2. Open plugin browser
3. Try searching

### System Info

All latest.

**Comment by itzTheMeow** [comment]
i found you have to click the refresh button in the top right for it to search

**Comment by nexpid** [comment]
fixed, will be pushed to github later

**Comment by nexpid** [comment]
https://github.com/nexpid/VendettaPlugins/commit/0b5dcf22bdced674a284723e38124a4b1fe088b5
