### ISSUE TITLE
bug(MonetTheme): Too many re-renders. React limits the number of renders to prevent an infinite loop.

### ISSUE THREAD

**Issue by LeftyDextrous** [nexpid/VendettaPlugins#56]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@leftydextrous

### Detailed Info

Any attempt to run Monet Theme results in the title message given in the Issue title. Retried several times.

### Steps to Reproduce

1. Install Vendetta
2. Install PluginBrowser
3. Install MonetTheme
4. Tap the settings cog for MonetTheme
5. Selector screen briefly appears, but quickly replaced by error screen showing message in Issue title

### Crash Info

`Too many re-renders. React limits the number of renders to prevent an infinite loop.`

### Bug Screenshot

![image](https://github.com/nexpid/VendettaPlugins/assets/121032844/3c16ec84-3226-4874-a0e6-1e9b6a342e55)
^Immediately after tapping cog
![image](https://github.com/nexpid/VendettaPlugins/assets/121032844/cbdbd8b0-7815-4314-b501-64d58e79308e)
^Resulting error message

### System Info

Device: oriole (Pixel 6)
Manufacturer: Google
Brand:  Google

OS: Android (GrapheneOS)
Version: 14

Discord Branch: Stable
Discord Version: 209.14
Discord Build: 20901400141590
Vendetta Version: Vendetta - 0e48cbc

React Version: 18.2.0
Hermes Bytecode: 94

Note: This has been filled in manually as I could not find any "sysinfo" plugin. I will amend this form as necessary.

**Comment by LeftyDextrous** [comment]
Edit: Minor cropping of top bar in screenshots.

**Comment by nexpid** [comment]
fixed 👍 will close once i push to github

**Comment by LeftyDextrous** [comment]
Thanks!
