### ISSUE TITLE
bug(plugin-browser): Error "Cannot read property useSearchControls of undefined" when opening the plugin

### ISSUE THREAD

**Issue by Idain** [nexpid/VendettaPlugins#58]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@\_idain\_

### Detailed Info

When trying to open the Plugin Browser, an error appears saying that it "Cannot read property useSearchControls of undefined" and doesn't show the plugin list.

### Steps to Reproduce

1. Go to Settings.
2. Open Plugin Browser. 

### Bug Screenshot

![Screenshot_20240125_220850_dev beefers vendetta](https://github.com/nexpid/VendettaPlugins/assets/54337884/06f12a23-ebde-40df-ac87-17802dbaea02)

### System Info

Device: HUAWEI JKM-LX3
Manufacturer: HUAWEI
Brand: HUAWEI

OS: Android
Version: 9

Discord Branch: googleRelease
Discord Version: 212.11
Discord Build: 212011
Vendetta Version: eed5355

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
fixed already just not committed

**Comment by nexpid** [comment]
thought that would work nvm, closed by 2813062b514651057754fcc7763de3b9d358b9b2
